//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Blog_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTbl
    {
        public int BlogId { get; set; }
        public int UserId { get; set; }
        public string Images { get; set; }
        public string Title { get; set; }
        public string Messages { get; set; }
        public System.DateTime TravelDate { get; set; }
        public string Details { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
